config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources  :posts,         only: [:index, :new, :create, :destroy, :show]
  resources  :relationships, only: [:create, :destroy]
  resources  :users,         only: [:index, :show]
  resources  :notifications, only: :index

  root to: 'posts#new'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :following, class_name: 'User', foreign_key: 'followed_id'

  validates :content, :followed_id, presence: true

  scope :includes_reversed_following, -> { includes(:following).reverse }

  def self.about_me(current_user_id)
    where(followed_id: current_user_id).includes(:following).reverse_order
  end

  def self.notifications_not_seen_counter(current_user_id)
    Notification.all.about_me(current_user_id).where(checked: false).count
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :content, presence: true
  scope :includes_reversed_user, -> { includes(:user).reverse }
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :user
  belongs_to :following, class_name: 'User', foreign_key: 'followed_id'
  validates :followed_id, presence: true

  def sends_user_follow_notification
    UserFollowNotificationWorker.perform_async(self.user_id, self.followed_id)
  end

  def sends_user_unfollow_notification
    UserUnfollowNotificationWorker.perform_async(self.user_id, self.followed_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "missing_:style.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_many :posts, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships
  has_many :followers_relationship, class_name: 'Relationship', foreign_key: 'followed_id'
  has_many :followers, through: :followers_relationship, source: :user

  def following?(user)
    self.relationships.pluck(:followed_id).include?(user.id)
  end

  def relationship(user)
    Relationship.where(user_id: self, followed_id: user).pluck(:id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  ensure_security_headers # See more: https://github.com/twitter/secureheaders

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :avatar) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :current_password, :avatar) }
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    @notifications = Notification.all.about_me(current_user.id)
    update_notifications
  end

  private
    def update_notifications
      @notifications.update_all(checked: true)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.includes_reversed_user
  end

  def new
    @posts = index
    @post  = current_user.posts.build if user_signed_in?
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to request.referer
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private
    def post_params
      params.require(:post).permit(:content)
    end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @relationship = current_user.relationships.create(followed_id: params[:followed_id])
    @relationship.sends_user_follow_notification
    redirect_to request.referer
  end

  def destroy
    @relationship = current_user.relationships.find(params[:id])
    @relationship.sends_user_unfollow_notification
    @relationship.destroy
    redirect_to request.referer
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @q ||= User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash_messages.html.slim
- flash.each do |key, value|
  div id="flash_#{key}"
    = value

app/views/layouts/_header.html.slim
#links
  - if user_signed_in?

    ul
      .signed
        li = link_to 'Minha conta', edit_user_registration_path
        li = link_to 'Sair', destroy_user_session_path, :method => :delete

  - else

    ul
      .not_signed
        li = link_to 'Cadastrar-se', new_user_registration_path
        li = link_to 'Entrar', new_user_session_path

#logo
  = link_to "MyWitter", root_path

- if user_signed_in?
  #notifications
    h1 = link_to "Notificações #{Notification.notifications_not_seen_counter(current_user.id)}", notifications_path

  #search
    = render 'users/form'

app/views/layouts/application.html.slim
doctype 5
html lang="pt"
  head
    meta charset="utf-8"
    meta name="keywords" content=""
    meta name="description" content=""

    title
      = page_title(app_name: 'MyWitter')

    link href="/favicon.ico" rel=("shortcut icon")

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    /![if lt IE 9]
      script src="http://html5shim.googlecode.com/svn/trunk/html5.js"

  header#header
    = render 'layouts/header'

  body class='body_class'
    #main
      = render 'flash_messages'
      = yield

app/views/notifications/index.html.slim
#notifications-index
  #profile-info-notifications
    = render 'users/profile'

#notifications-timeline
  h1 Notificações
  - if @notifications.any?
    - @notifications.each do |notification|
      ul#header
        li = image_tag notification.user.avatar.url(:thumb), id: 'round-image-50'
        li
          h1 = link_to notification.user.email, user_path(notification.user)

      p = notification.content

      ul#footer
        li
          #label
            label = "há #{time_ago_in_words(notification.created_at)}"
        li
          #followings_links
            = render 'users/followings_links', user: notification.user
      hr

  - else
    h1 Nenhuma notificação até o momento :(

app/views/posts/_form.html.slim
= simple_form_for(@post) do |f|
  = f.input :content, label: false
  = f.submit 'Postar', class: 'form-actions'

app/views/posts/_index.html.slim
h1 Timeline
- if posts.any?
  - posts.each do |post|
    ul#header
      li = image_tag post.user.avatar.url(:thumb), id: 'round-image-50'
      li
        h1= link_to "#{post.user.email}", post_path(post), id: 'email'

    p = post.content

    ul#footer
      li
        #label
          label = "há #{time_ago_in_words(post.created_at)}"
      li
        #followings_links
          = render 'users/followings_links', user: post.user
    hr

- else
  h1 Nenhuma postagem até o momento :(

app/views/posts/new.html.slim
- if user_signed_in?
  #new-post
    h1 Cê tá pensando em que? :)
    = render 'form'

    #profile-info
      = render 'users/profile'

#index
  = render 'index', posts: @posts

app/views/posts/show.html.slim
#post-show
  h4 Post
  ul#header
    li = image_tag @post.user.avatar.url(:thumb), id: 'round-image-50'
    li
      h1= link_to "#{@post.user.email}", user_path(@post.user), id: 'email'

  p = @post.content

  ul#footer
    li
      #label
        label = "há #{time_ago_in_words(@post.created_at)}"
    li
      #follow_link
      	= render 'users/followings_links', user: @post.user
  = link_to 'Voltar', request.referer

app/views/users/_followings_links.html.slim
- if user_signed_in?
  - unless current_user.eql?(user)
    - if current_user.following?(user)
      = link_to 'Deixar de seguir', relationship_path(current_user.relationship(user)), method: :delete
    - else
      = link_to 'Seguir', relationships_path(followed_id: user.id), method: :post

app/views/users/_form.html.slim
= simple_form_for @q ||= User.ransack, :url => users_path, :html => {:method => :get} do |f|
  #search-input
    = f.input :email_cont, label: false, placeholder: 'Encontre amigos'

  #submit-button
    = f.submit 'Buscar'

app/views/users/_profile.html.slim
#profile
  = image_tag current_user.avatar.url(:medium), id: 'round-image-150'
  h1 = link_to current_user.email, current_user

  ul
    li = "Posts #{current_user.posts.count} |"
    li = "Seguidores #{ current_user.followers.count } |"
    li = "Seguindo #{ current_user.followings.count }"

app/views/users/index.html.slim
#user-index
  h1 Usuários
  - if @users.any?
    - @users.each do |user|

        = image_tag user.avatar.url(:medium), id: 'round-image-50'
        h1 = link_to user.email, user
        #follow_link
          = render 'followings_links', user: user
  - else
    h1 Nenhum membro encontrado :(

app/views/users/show.html.slim
#user-show
  #user-header
  = image_tag @user.avatar.url(:medium), id: 'round-image-150'
  h1 = link_to @user.email, @user
  = render 'followings_links', user: @user

  h1 = "Seguidores #{ @user.followers.count }"
  ul
  - @user.followers.each do |follower|
    li = link_to (image_tag(follower.avatar.url(:thumb), alt: "#{follower.email}", id: 'round-image-50')), follower

  h1 = "Seguindo #{ @user.followings.count }"
  ul
  - @user.followings.each do |followed|
    li = link_to (image_tag(followed.avatar.url(:thumb), alt: "#{followed.email}", id: 'round-image-50')), followed

#user-posts
  = render 'posts/index', posts: @user.posts.reverse